name: ci
on: page_build
jobs:
  linkinator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: JustinBeckwith/linkinator-action@v2
        with:
          paths: https://jasonhemann.github.io/26SP-CS3204
          config: linkinator.config.json
